# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.fields import ArrayField


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=2, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("website_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="providers", to="scholarships.country")),
            ],
            options={
                "ordering": ["name"],
                "constraints": [models.UniqueConstraint(fields=("name", "country"), name="unique_provider_name_country")],
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("degree_levels", ArrayField(base_field=models.CharField(choices=[("BACHELORS", "Bachelor's"), ("MASTERS", "Master's"), ("PHD", "PhD")], max_length=20), default=list)),
                ("funding_type", models.CharField(choices=[("FULLY_FUNDED", "Fully funded"), ("PARTIALLY_FUNDED", "Partially funded"), ("TUITION_ONLY", "Tuition only"), ("STIPEND", "Stipend")], max_length=30)),
                ("tuition_info", models.TextField(blank=True)),
                ("stipend_info", models.TextField(blank=True)),
                ("other_funding_info", models.TextField(blank=True)),
                ("eligibility", models.TextField()),
                ("academic_requirements", models.TextField(blank=True)),
                ("language_requirements", models.TextField(blank=True)),
                ("opening_date", models.DateField(blank=True, null=True)),
                ("deadline", models.DateField()),
                ("official_application_url", models.URLField()),
                ("official_source_url", models.URLField()),
                ("programme_catalogue_url", models.URLField(blank=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("VERIFIED", "Verified"), ("PUBLISHED", "Published"), ("CLOSED", "Closed")], default="DRAFT", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="scholarships", to="scholarships.provider")),
            ],
            options={
                "ordering": ["deadline", "name"],
                "indexes": [
                    models.Index(fields=["status"], name="scholarships_status_4d9b3a_idx"),
                    models.Index(fields=["deadline"], name="scholarships_deadline_3d8f8a_idx"),
                    models.Index(fields=["opening_date"], name="scholarships_opening_0d5b93_idx"),
                    models.Index(fields=["provider"], name="scholarships_provider_7c9b3e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("university", models.CharField(max_length=255)),
                ("official_url", models.URLField()),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="programs", to="scholarships.country")),
                ("scholarship", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="programs", to="scholarships.scholarship")),
            ],
            options={"ordering": ["university", "name"]},
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("ACADEMIC", "Academic"), ("LANGUAGE", "Language"), ("DOCUMENT", "Document"), ("ELIGIBILITY", "Eligibility"), ("FINANCIAL", "Financial"), ("OTHER", "Other")], max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("required", models.BooleanField(default=True)),
                ("scholarship", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="requirements", to="scholarships.scholarship")),
            ],
            options={
                "ordering": ["type", "title"],
                "indexes": [models.Index(fields=["scholarship", "type"], name="scholarships_scholarship_7c6b43_idx")],
            },
        ),
        migrations.AddField(
            model_name="scholarship",
            name="fields",
            field=models.ManyToManyField(blank=True, related_name="scholarships", to="scholarships.field"),
        ),
    ]
