# Generated by Django 5.2

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="requirement",
            new_name="scholarship_scholar_999c2a_idx",
            old_name="scholarships_scholarship_7c6b43_idx",
        ),
        migrations.RenameIndex(
            model_name="scholarship",
            new_name="scholarship_status_925bc3_idx",
            old_name="scholarships_status_4d9b3a_idx",
        ),
        migrations.RenameIndex(
            model_name="scholarship",
            new_name="scholarship_deadlin_f24616_idx",
            old_name="scholarships_deadline_3d8f8a_idx",
        ),
        migrations.RenameIndex(
            model_name="scholarship",
            new_name="scholarship_opening_68dafd_idx",
            old_name="scholarships_opening_0d5b93_idx",
        ),
    ]
