"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Scholarship = {
  id:number; name:string; provider:string; country:string; degree_levels:string[]; funding_type:string; description:string; deadline:string; days_remaining:number|null; status:string; eligibility:string; academic_requirements:string; language_requirements:string; tuition_info:string; stipend_info:string; official_application_url:string; official_source_url:string; last_verified_at:string|null;
};

const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL ?? "";
const funding:Record<string,string>={FULLY_FUNDED:"Fully funded",PARTIALLY_FUNDED:"Partially funded",TUITION_ONLY:"Tuition only",STIPEND:"Stipend"};
const degree:Record<string,string>={BACHELORS:"Bachelor's",MASTERS:"Master's",PHD:"PhD"};

export default function ScholarshipDetail({params}:{params:Promise<{id:string}>}){
  const [item,setItem]=useState<Scholarship|null>(null); const [error,setError]=useState(false); const [loading,setLoading]=useState(true);
  useEffect(()=>{void params.then(async({id})=>{try{const r=await fetch(API_BASE+"/api/scholarships/"+id+"/",{credentials:"include"});if(!r.ok)throw new Error();setItem(await r.json());}catch{setError(true);}finally{setLoading(false);}})},[params]);
  if(loading)return <main className="min-h-screen bg-[#0b0f19] p-8 text-white">Loading scholarship...</main>;
  if(error||!item)return <main className="min-h-screen bg-[#0b0f19] p-8 text-white"><Link href="/" className="text-blue-400">← Back to scholarships</Link><div className="mx-auto mt-20 max-w-xl text-center"><h1 className="text-xl font-bold">Scholarship not found</h1><p className="mt-2 text-sm text-slate-400">This scholarship is unavailable or is not published.</p></div></main>;
  return <main className="min-h-screen bg-[#0b0f19] text-white"><div className="bg-glow"/><header className="glass-surface border-x-0 border-t-0"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8"><Link href="/" className="text-lg font-bold">Scholar<span className="text-blue-400">Track</span></Link><Link href="/" className="text-sm text-slate-400 hover:text-white">← Back to scholarships</Link></div></header><div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><p className="text-xs text-blue-400">{item.provider} · {item.country}</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{item.name}</h1><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-xs">{funding[item.funding_type]??item.funding_type}</span><span className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-xs">{item.degree_levels.map(v=>degree[v]??v).join(", ")}</span><span className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-xs">{item.deadline}</span></div><div className="mt-8 grid gap-5 lg:grid-cols-[1fr_320px]"><article className="glass-surface rounded-2xl p-6 space-y-7"><section><h2 className="font-semibold">Overview</h2><p className="mt-2 text-sm leading-6 text-slate-400">{item.description}</p></section><section><h2 className="font-semibold">Eligibility</h2><p className="mt-2 whitespace-pre-line text-sm leading-6 text-slate-400">{item.eligibility}</p></section><section><h2 className="font-semibold">Academic requirements</h2><p className="mt-2 whitespace-pre-line text-sm leading-6 text-slate-400">{item.academic_requirements||"See official source for academic requirements."}</p></section><section><h2 className="font-semibold">Language requirements</h2><p className="mt-2 whitespace-pre-line text-sm leading-6 text-slate-400">{item.language_requirements||"See official source for language requirements."}</p></section></article><aside className="space-y-4"><div className="glass-surface rounded-2xl p-5"><p className="text-xs uppercase tracking-wider text-slate-500">Deadline</p><p className="mt-2 text-xl font-bold">{item.deadline}</p><p className="mt-1 text-xs text-blue-300">{item.days_remaining===null?"Closed":item.days_remaining===0?"Deadline today":item.days_remaining+" days remaining"}</p><a href={item.official_application_url} target="_blank" rel="noreferrer" className="btn-primary mt-5 flex justify-center rounded-xl px-4 py-3 text-sm font-semibold">Apply on official site</a><a href={item.official_source_url} target="_blank" rel="noreferrer" className="mt-2 flex justify-center rounded-xl border border-white/10 px-4 py-3 text-sm font-semibold text-slate-300 hover:bg-white/5">Official source</a></div>{item.last_verified_at&&<div className="glass-surface rounded-2xl p-5 text-xs text-slate-400">Last verified: {new Date(item.last_verified_at).toLocaleDateString()}</div>}</aside></div></div></main>;
}
